[package]
name = "exp-move"
version = "0.0.0"

[addresses]
Std = "0x1"

[dependencies]
MoveNursery = { git = "https://github.com/diem/diem.git", subdir = "language/move-stdlib/nursery", rev = "d45f20a" }
